version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
workflows:
  publish_etl:
    jobs:
    - build_and_deploy_glue_code
jobs:
  build_and_deploy_glue_code:
    docker:
    - image: cimg/python:3.7
    steps:
    - checkout
    - run:
        name: Install dependencies
        working_directory: etl
        command: pip install -r requirements.txt
    - run:
        name: Install Glue modules
        working_directory: etl
        command: ./add_glue_modules.py
    - run:
        name: Install self
        working_directory: etl
        command: pip install .
    - run:
        name: Lint
        working_directory: etl
        command: pylint src/ --rcfile=.pylintrc
    - run:
        name: Run unit tests
        working_directory: etl
        command: python -m pytest --ignore=integration_tests
    - run:
        name: Package files
        working_directory: etl
        command: python setup.py bdist_wheel
    - aws-s3/copy:
        from: etl/dist/cory.etl-0.0.1-py3-none-any.whl
        to: 's3://glue-learning-jobs-source/'
    - aws-s3/copy:
        from: etl/src/jobs/*
        to: 's3://glue-learning-jobs-source/'
