version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
workflows:
  publish_etl:
    jobs:
    - build
jobs:
  build:
    docker:
    - image: cimg/python:3.7
    steps:
    - checkout
    - run:
        command: pip install -r requirements.txt
        working_directory: etl
    - run:
        command: python -m pytest
        working_directory: etl
    - run:
        command: python setup.py bdist_wheel
        working_directory: etl
